apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kasm.fullname" . }}
  labels:
    {{- include "kasm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kasm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kasm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kasm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VNC_PW
            value: {{ .Values.vncpass }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: install
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/__healthcheck
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 360
          readinessProbe: 
            httpGet:
              path: /
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
