{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kasm
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "kasm.fullname" . }}
  trafficPolicy:
    tls:
      mode: SIMPLE
{{- end }}