{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kasm
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
    - {{ tpl . $}}
  {{- end }}
  gateways:
    - istio-system/dataplane
  http:
    - route:
        - destination:
            host: {{ include "kasm.fullname" . }}
            port:
              number: 8080
{{- end }}